<?php namespace JF;
/**

Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-4cfb7c
Date:    2016-10-25 11:36:25
Version: v1.0-rc24
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-4cfb7c",
    "email": {
        "to": "fnb@saltydog.com",
        "cc": "",
        "bcc": "rob@saltydog.com",
        "subject": "{c25} - {c33} - {c188} - {c38}",
        "template": "",
        "sendmail_from": "salesreports@saltydog.com"
    },
    "admin": {
        "users": "admin:9e34e",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "Your sales have been sent. Thank You!",
        "seconds": "10"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "smtp",
    "smtp": {
      "host": "mail.saltydog.com",
        "user": "sales@saltydog.com",
        "password": "Uapg62_8",
        "port": "25",
        "security": "none"
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [

    ],
    "fields": [
     {
            "label": "Date",
            "field_type": "text",
            "required": false,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "mask": {
              
                }
            },
            "cid": "c164"
        },
        {
            "label": "Location",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "The Cafe",
                        "value": "cafe",
                        "checked": false
                    },
                    {
                        "label": "Land's End Tavern",
                        "checked": false,
                        "value": "let"
                    },
                    {
                        "label": "The Wreck",
                        "checked": false,
                        "value": "wreck"
                    },
                    {
                        "label": "Bluffdog",
                        "checked": false,
                        "value": "bluffdog"
                    },
                    {
                        "label": "Ice Cream",
                        "value": "ic",
                        "checked": null
                    },
                     {
                        "label": "Cruise",
                        "value": "cruise",
                        "checked": null
                    },
                    {
                        "label": "Pizza",
                        "value": "pizza",
                        "checked": null
                    },
                    {
                        "label": "Other",
                        "value": "other",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c25"
        },
        {
            "label": "Net Sales",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "pattern": {
                        "enabled": false,
                        "val": "9999999.99"
                    },
                    "equalto": {
                        "enabled": false
                    }
                },
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c33"
        },
        {
            "label": "Person Completing Form",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "mask": {
                    "pattern": "S"
                }
            },
            "cid": "c38"
        },
         {
            "label": "Shift",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Mid-Day",
                        "value": "mid-day",
                        "checked": false
                    },
                    {
                        "label": "End of Day",
                        "checked": false,
                        "value": "end-of-day"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c188"
        },
       
        {
            "label": "F&B Sales Info",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "cid": "c43"
        },
        {
            "label": "Breakfast Net",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c48"
        },
        {
            "label": "Breakfast Covers",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c53"
        },
        {
            "label": "Breakfast Average",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c58"
        },
        {
            "label": "Lunch Net",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c63"
        },
        {
            "label": "Lunch Covers",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c68"
        },
        {
            "label": "Lunch Average",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c73"
        },
        {
            "label": "Dinner Net",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c78"
        },
        {
            "label": "Dinner Covers",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c83"
        },
        {
            "label": "Dinner Average",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c88"
        },
        {
            "label": "Cruise F&B",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c98"
        },
        {
            "label": "Cruise Tickets",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c103"
        },
        {
            "label": "Cruise Passengers",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c108"
        },
        {
            "label": "Cruise Crew",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ],
                "mask": {
                    "pattern": "#"
                }
            },
            "cid": "c113"
        },
        {
            "label": "Notes\/Comp Reports",
            "field_type": "section_break",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "cid": "c118"
        },
        {
            "label": "AM Floor Lead",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c123"
        },
        {
            "label": "AM Kitchen Lead",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c128"
        },
        {
            "label": "PM Floor Lead",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c133"
        },
        {
            "label": "PM Kitchen Lead",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small",
                "addon": [

                ]
            },
            "cid": "c138"
        },
        {
            "label": "Notes",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                },
                "size": "small"
            },
            "cid": "c250"
        },
        {
            "label": "Google reCaptcha",
            "field_type": "recaptcha",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [

                    ],
                    "slideshow": false
                }
            },
            "labelHide": true,
            "recaptcha": {
                "theme": "light",
                "siteKey": "6Lfh5RcTAAAAAMjyPmZ8xEcF5bwG3uyMDMO7xRV9",
                "secretKey": "6Lfh5RcTAAAAAEsxV5vUdOT5LsBbEXlPAvkj_T9T",
                "language": ""
            },
            "cid": "c143"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "cid": "c100"
        }
    ]
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class