<?php namespace JF;
/**

Copyright 2019 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-386d1b
Date:    2019-06-21 14:41:07
Version: v3.0.2
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-386d1b",
    "email": {
        "to": "patrol@saltydog.com",
        "cc": "",
        "bcc": "",
        "subject": "{f5} Patrol Report",
        "template": "",
        "sendmail_from": ""
    },
    "admin": {
        "users": "admin:d1278",
        "dataDelivery": "emailOnly"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": "",
        "replyTo": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Patrol Person",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": ""
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Date",
            "field_type": "date",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "addon": {
                    "rightIcon": "glyphicon glyphicon-th",
                    "rightText": "",
                    "leftIcon": "fa fa-calendar"
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": ""
            },
            "id": "f5",
            "cid": "c31"
        },
        {
            "label": "Time Reported",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-time"
                }
            },
            "id": "f6",
            "cid": "c36"
        },
        {
            "label": "Weather",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-sun-o"
                }
            },
            "id": "f7",
            "cid": "c41"
        },
        {
            "label": "Fire Watch",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f37",
            "cid": "c114"
        },
        {
            "label": "The Inn Grounds",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-hotel"
                }
            },
            "id": "f9",
            "cid": "c52"
        },
        {
            "label": "Marina Entrance Points",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-globe"
                }
            },
            "id": "f10",
            "cid": "c57"
        },
        {
            "label": "Parking Lots",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-car"
                }
            },
            "id": "f11",
            "cid": "c62"
        },
        {
            "label": "Bathrooms",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-female"
                }
            },
            "id": "f12",
            "cid": "c67"
        },
        {
            "label": "Outdoor Cafe\/Deck",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-tv"
                }
            },
            "id": "f13",
            "cid": "c72"
        },
        {
            "label": "Docks",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftText": "",
                    "leftIcon": "fa fa-ship"
                }
            },
            "id": "f14",
            "cid": "c77"
        },
        {
            "label": "Pool",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-life-saver"
                }
            },
            "id": "f15",
            "cid": "c82"
        },
        {
            "label": "Unusual Incident\/Open or Unlocked Doors",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f36",
            "cid": "c114"
        },
        {
            "label": "Photo of Incident",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                },
                "multiple": true
            },
            "id": "f21",
            "cid": "c112"
        },
        {
            "label": "Maintenance Issues\/Needs",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f32",
            "cid": "c114"
        },
        {
            "label": "Photo of Maintenance Issue\/Need",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true
                }
            },
            "id": "f29",
            "cid": "c158"
        },
        {
            "label": "Damaged\/Vandalized Property",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f33",
            "cid": "c120"
        },
        {
            "label": "Photo of Damage or Vandalism",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                },
                "multiple": true
            },
            "id": "f23",
            "cid": "c122"
        },
        {
            "label": "Guest's Comments\/Suggestions",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f34",
            "cid": "c126"
        },
        {
            "label": "Lost & Found Items",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f25",
            "cid": "c132"
        },
        {
            "label": "Photo of Found Items",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                }
            },
            "id": "f26",
            "cid": "c137"
        },
        {
            "label": "Additional Photo",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "maxFileCount": "5",
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                },
                "multiple": true
            },
            "id": "f28",
            "cid": "c147"
        },
        {
            "label": "Additional Photo",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                },
                "multiple": true
            },
            "id": "f30",
            "cid": "c110"
        },
        {
            "label": "Additional Photo",
            "field_type": "file",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "file": {
                    "showPreview": true,
                    "showRemove": true,
                    "allowedFileExtensions": "png,jpg,jpeg,svg,bmp,gif,tif,tiff,raw,nef,cr2,crw,dng,srf,arw"
                },
                "multiple": true
            },
            "id": "f31",
            "cid": "c115"
        },
        {
            "label": "Description\/Explanation of Additional Photos",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f35",
            "cid": "c132"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": "",
    "copyFrom": "jqueryform-f321f3"
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class